### ISSUE TITLE
explicit

### ISSUE THREAD

**Issue by cyberspace22** [VerifiableRobotics/slugs#19]
When I run the example water_reservoir.slugsin file in the slug with explicitStrategy, the output is the file attached. What do the values level@1, level@2, etc., mean? Is it possible to find the level of the reservoir at every state? If so, how?

[water_reservoir.txt](https://github.com/VerifiableRobotics/slugs/files/570635/water_reservoir.txt)

**Comment by cyberspace22** [comment]
[water_reservoir.txt](https://github.com/VerifiableRobotics/slugs/files/570633/water_reservoir.txt)

**Comment by progirep** [comment]
Hi cyberspace22, 

The file "water_reservoir.slugsin" is generated from the human-readable "water_reservoir.structuredslugs" specification by the "StructuredSlugsCompiler" script. Since the structuredslugs format support integers, but the standard format does not, this means that all integer variables need to be binary-encoded. All variables with an "@" in them are such encoded variables. @johnyf was so nice to write some documentation of the encoding, which can be found [here](https://github.com/VerifiableRobotics/slugs/blob/master/doc/input_formats.md). The structuredslugs format (but not its binary encoding) is also described in the slugs tool paper.

Having said that, you are right in that the generated implementation is now not particularly easy to read. But luckily I wrote a Python script to decode the integer values last week anyway. I just added it to the master branch of slugs under the name "tools/explicitImplementationIntegerDecoder.py". If you run

`tools/explicitImplementationIntegerDecoder.py < automatonFile > resultingInterpretedAutomataFile`

you will receive a new file for the synthesized implementation that looks like this:

```
State 0 with rank 0 -> <inflow1:0, inflow2:0, level=10, outflow:0>
	With successors : 0, 1, 2, 3
State 1 with rank 0 -> <inflow1:0, inflow2:1, level=10, outflow:0>
	With successors : 4, 5
State 2 with rank 0 -> <inflow1:1, inflow2:0, level=10, outflow:0>
	With successors : 4, 6
State 3 with rank 0 -> <inflow1:1, inflow2:1, level=10, outflow:0>
	With successors : 7
State 4 with rank 0 -> <inflow1:0, inflow2:0, level=12, outflow:0>
	With successors : 4, 6, 5, 8
```

This one should now be much easier to read. Note that the separating character "=" is used for integer variables, and the ":" is used for all boolean variables.
