### ISSUE TITLE
Backwards reachability computations do not enforce env safety unless "next" is used?

### ISSUE THREAD

**Issue by spmaniato** [VerifiableRobotics/slugs#5]
This is more of a kink than a bug:

In the following automaton, the environment is seemingly allowed to falsify one of its own safety requirements, specifically the mutex statement: `[](s1 <-> !s2)` (This is part of a larger LTLMoP specification. Please ask for the .spec file if it'd be helpful.)

The issue is resolved if the env safety is written in the "next" tense: `[](next(s1) <-> next(!s2))`

According to @vraman 

> The reason these states get generated is because the backwards reachability computations start from any winning states, including states from which the environment cannot move, and then add in transitions that do not violate the environment safety. The two states you point out are winning states, and included in this computation. Now, the transitions into these "dead" states do not technically violate the env safety unless the safety is expressed with a "next" operator. In other words, the transition still satisfies your original safety, even though the resulting state does not. 

Not sure if it merits fixing, but seemed worth documenting.

![kink](https://cloud.githubusercontent.com/assets/2285973/5093624/22eca758-6f28-11e4-970a-63deef36b9b6.png)

![kink_fixed](https://cloud.githubusercontent.com/assets/2285973/5093900/26cbb3b2-6f2a-11e4-8d2c-4789cd653ab1.png)

**Comment by johnyf** [comment]
Strictly speaking, the environment cannot change the value of the expression `s1 <-> !s2`, because it has happened in the past, so the values of `s1` and `s2` are fixed. They must be primed `s1' <-> !s2'` to be future valuations that the environment can select. In other words, the node `(!a1, a2)` in the game graph is losing for the environment, so if it happens to start there, then it has already lost (thus no outgoing edges from that node), since it can't change the past.

Perhaps trimming deadends until there are none left can avoid this issue.

An example that demonstrates such a situation is the following spec:
```
[INPUT]
x
y

[ENV_INIT]
^ x ! y

[ENV_TRANS]
! ^ x ! y

[SYS_LIVENESS]
0
```
is realizable, returning, as of 45102830c21614b669517bfceefd5214662813a5, the strategy:
```
{"version": 0,
 "slugs": "0.0.1",

 "variables": ["x", "y"],

 "nodes": {
"0": {
	"rank": 0,
	"state": [0, 0],
	"trans": []
},

"1": {
	"rank": 0,
	"state": [0, 1],
	"trans": [0, 3]
},

"2": {
	"rank": 0,
	"state": [1, 0],
	"trans": [0, 3]
},

"3": {
	"rank": 0,
	"state": [1, 1],
	"trans": []
}

}}
```
whereas the spec:
```
[INPUT]
x
y

[ENV_INIT]
^ x ! y

[ENV_TRANS]
! ^ x ! y'

[SYS_LIVENESS]
0
```
is not realizable, because the environment can react to the initial valuation `^ x ! y` by setting the *future* value of the variable `y`.

**Comment by vraman** [comment]
On Thu, Jan 15, 2015 at 7:42 PM, Ioannis Filippidis <
notifications@github.com> wrote:

> Strictly speaking, the environment cannot change the value of the
> expression s1 <-> !s2, because it has happened in the past, so the values
> of s1 and s2 are fixed.
>
I'm not sure this is the right way of thinking about this, since there are
situations where you would want to enforce specifications on states (i.e.
"current" valuation) instead of transitions (i.e. "next" valuation).
Rather, the winning strategy for the system includes all states that
violate s1 <-> !s2,and since environment safety does not specify s1' <->
!s2', transitions into these states (which would violate s1' <-> !s2') are
also allowed.

Vasu

**Comment by progirep** [comment]
The dead end in the automaton is due to the special semantics of GR(1). In particular, the generate specification must ensure that the guarantees are not violated "before" the assumptions are violated. Now if we see "A -> G" as an LTL formula, where A defines the assumptions, and G defines the guarantees, the idea of violating A "before" G does not make sense - Temporal logic does not have a "Before" operator that can be used in this case because due to the fact that A talks about an infinite suffix and so does G, we can't say that something about "A" happens before something about "G".

This is actually subject to a pretty comprehensive paper by Uri Klein, where he explains this in details. Now GR(1) still uses this idea the the guarantees must not be violated "before" the assumptions are violated - this makes the game a bit easier and actually helps with encoding more complex specifications to GR(1). I've sometimes made this explicit by writing "A ->_s G" in some papers, where "->_s" is the strict implication operator as defined in the journal version of the paper that introduces GR(1) (the one with R. Bloem as co-author). Intuitively, for the GR(1) semantics, "before" means that it should not become "obvious" that the guarantees are violated before it becomes obvious that the assumptions are violated. Now when the environment plays "!(s1 <-> !s2)", it takes one more step before the violation of the transition constraint becomes obvious (because no unallowed transition has been taken yet) - thus the system is required to give another output valuation that does not violate its transition constraint. Thus, a transition to the deadlock is added.

Because the strict implication makes encoding more complex properties easier, it made sense for slugs to stick to the standard GR(1) semantics and actually add the node -- otherwise we couldn't claim to have a GR(1) synthesis tool. If in some application, you don't need the dead-end, it should be easy to strip away. Now we could offer an option to strip the dead-end away in the tool. As this mixes up strict implication semantics and non-strict implication semantics, on a semantic level, understanding what this option does is actually confusing, so this change is not on top of the TODO-list.

**Comment by progirep** [comment]
I'm closing this issue as I think that the discussion will probably not resume.
